def main() -> None:
    print()
    print("""
                .,:clooooolc;,.
               ;ooloooooooooooo:.
              ;oc   loooooooooooo.
              :oo,.,ooooooooooooo.
              ,:::::::::ooooooooo.
       .,;::::::::::::::ooooooooo. ....
     .loooooooooooooooooooooooooo. .......
    .oooooooooooooooooooooooooooo. ........
    :ooooooooooooooooooooooooooo; .........
    ooooooooooool;,,,,,,,,,,,,.. ...........
    looooooooo,  ...........................
    ;oooooooo. ............................
     oooooooo .............................
     .coooooo ............................
        ..... ..........
              ...................
              ..............   ..
               .............   ..
                 ..............
                    .......
    """)
    import this
    print()

if __name__ == "__main__":
    main()

